# Generated by Django 2.0.3 on 2019-01-16 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20190115_0325'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookname', models.CharField(max_length=128)),
                ('auther', models.CharField(max_length=128)),
                ('format', models.CharField(max_length=64)),
                ('path', models.CharField(max_length=128)),
            ],
        ),
    ]
