# Generated by Django 2.0.3 on 2019-01-17 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_booklist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookList',
        ),
    ]
