# Generated by Django 2.0.3 on 2019-01-18 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20190118_0208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booklist',
            name='location',
        ),
    ]
