# Generated by Django 2.0.3 on 2019-01-18 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_remove_booklist_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='booklist',
            name='location',
            field=models.CharField(default='1', max_length=4),
        ),
    ]
